---
Name: postageconfig
---
## Extensions
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\Postage\Extensions\SiteConfigExtension
SilverCommerce\GeoZones\Model\Zone:
  extensions:
    - SilverCommerce\Postage\Extensions\ZoneExtension