---
Name: postageconfig
---
## Extensions
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\Postage\Extensions\SiteConfigExtension
SilverCommerce\OrdersAdmin\Model\Estimate:
  extensions:
    - SilverCommerce\Postage\Extensions\PostageExtension